syntax on
filetype plugin indent on

if filereadable(expand("~/.vimrc.plugins"))
  source ~/.vimrc.plugins
endif

" set termguicolors
set background=dark
set encoding=UTF-8
set fileencodings=utf-8
set number
set cursorline
set wildmenu
set expandtab
set tabstop=2
set smartindent
set shiftwidth=2
set showmatch
set clipboard=unnamed
set noswapfile
set list
set listchars=tab:»-,space:_,eol:↲
set infercase
set hidden
set switchbuf=useopen
set ignorecase
set smartcase
set incsearch
set hlsearch
set mouse=a
set ambiwidth=double
set backspace=2

" Emacs key binds
imap <C-p> <Up>
imap <C-n> <Down>
imap <C-b> <Left>
imap <C-f> <Right>

" Split window
nmap ss :split<Return><C-w>w
nmap sv :vsplit<Return><C-w>w

" Switch tab
nnoremap <S-Tab> :tabprev<Return>
nnoremap <Tab> :tabnext<Return>

" Move window
map sh <C-w>h
map sk <C-w>k
map sj <C-w>j
map sl <C-w>l

" Copy Relative Path
nmap rp :let @+ = expand("%")<Return>

" colorscheme
colorscheme gruvbox
