require('plugins')
require('plugins.gitsigns-config')
require('plugins.lualine-config')
require('plugins.nightfox')
require('plugins.nvim-autopairs-config')
require('plugins.nvim-cmp-config')
require('plugins.mason-config')
-- require('plugins.null-ls-config')
require('plugins.nvim-lspconfig-config')
require('plugins.nvim-tree-config')
require('plugins.nvim-treesitter-config')
require('plugins.telescope-config')
require('plugins.toggleterm-config')
require('plugins.trouble-config')
